version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: green_waste_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
